-- 关闭所有表的 RLS，允许匿名访问
ALTER TABLE "Student" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Project" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "TestRecord" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ScoreStandard" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "AppConfig" DISABLE ROW LEVEL SECURITY;
